### PR TITLE
Update CITATION.bib

### PR DESCRIPTION
**Pull request by dlfivefifty**
I followed the link and it looks like the Journal name was wrong...

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks. That win32 error is weird to say the least...

**Comment by ChrisRackauckas** [comment]
@asinghvi17 is every CITATION.bib the same?

**Comment by asinghvi17** [comment]
Yeah it should be...do you still have that script I sent you?

**Comment by ChrisRackauckas** [comment]
I don't think so. Not if it's not in a PR somewhere.

**Comment by asinghvi17** [comment]
Will look around on my laptop for it.

**Comment by asinghvi17** [comment]
[scriptonorg.txt](https://github.com/JuliaDiffEq/DifferentialEquations.jl/files/3855836/scriptonorg.txt)

This should be the script, but let me know if it fails.

**Comment by ChrisRackauckas** [comment]
Looks like this worked:

```julia
# setup
using Base64

"Converts the contents of a file returned by GitHub's API to a String."
file2string(s64::AbstractString) = split(s64, "\n") .|> Base64.base64decode .|> String |> join

const incorrect_c = """@article{DifferentialEquations.jl-2017,
 author = {Rackauckas, Christopher and Nie, Qing},
 doi = {10.5334/jors.151},
 journal = {The Journal of Open Source Software},
 keywords = {Applied Mathematics},
 note = {Exported from https://app.dimensions.ai on 2019/05/05},
 number = {1},
 pages = {},
 title = {DifferentialEquations.jl – A Performant and Feature-Rich Ecosystem for Solving Differential Equations in Julia},
 url = {https://app.dimensions.ai/details/publication/pub.1085583166 and http://openresearchsoftware.metajnl.com/articles/10.5334/jors.151/galley/245/download/},
 volume = {5},
 year = {2017}
}"""

const correct_c = """@article{DifferentialEquations.jl-2017,
 author = {Rackauckas, Christopher and Nie, Qing},
 doi = {10.5334/jors.151},
 journal = {The Journal of Open Research Software},
 keywords = {Applied Mathematics},
 note = {Exported from https://app.dimensions.ai on 2019/05/05},
 number = {1},
 pages = {},
 title = {DifferentialEquations.jl – A Performant and Feature-Rich Ecosystem for Solving Differential Equations in Julia},
 url = {https://app.dimensions.ai/details/publication/pub.1085583166 and http://openresearchsoftware.metajnl.com/articles/10.5334/jors.151/galley/245/download/},
 volume = {5},
 year = {2017}
}"""

# github
import GitHub

auth = GitHub.authenticate("ENV["GITHUB_AUTH"]") # you need to set this in your ENV

printstyled("Acquiring ", color = 2, bold = true); println("JuliaDiffEq repos")

"All the repos in the org"
drepos = GitHub.repos("JuliaDiffEq", auth = auth)[1]

@info("$(length(drepos)) repos acquired")

"The repositories that have been modified successfully."
mrepos = GitHub.Repo[]

original_file = nothing

for r in drepos

    if r.name == "PoissonRandom.jl"
        continue
    end

    printstyled("Checking ", color = 2, bold = true); println(r.name)

    global original_file # for debugging if needed - this is not meant for much reuse

    try

        original_file = GitHub.file(r, "CITATION.bib", auth = auth)

    catch e

        printstyled("No CITATION.bib found\n", color = 1) # if no citation is found, don't do anything

        continue

    end

    original_citation = original_file.content |> file2string

    new_citation = replace(original_citation, incorrect_c => correct_c)

    github_new_citation = Base64.base64encode(new_citation)

    GitHub.update_file(r,
                    "CITATION.bib",
                    params = Dict(
                            :message => "Add journal to CITATION.bib",
                            :content => github_new_citation,
                            :sha => original_file.sha),
                    auth = auth
    )

    push!(mrepos, r)

end

mrepos
```

**Comment by asinghvi17** [comment]
Cool - you can use GitHub.create_file to add CompatHelper in the same way.

**Comment by ChrisRackauckas** [comment]
What I did was a little hacky but it worked:

```julia
# setup
using Base64

"Converts the contents of a file returned by GitHub's API to a String."
file2string(s64::AbstractString) = split(s64, "\n") .|> Base64.base64decode .|> String |> join

const correct_c = raw"""name: CompatHelper

on:
  schedule:
    - cron: '00 * * * *'
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'"""

# github
import GitHub

auth = GitHub.authenticate("ENV["GITHUB_AUTH"]") # you need to set this in your ENV

printstyled("Acquiring ", color = 2, bold = true); println("JuliaDiffEq repos")

"All the repos in the org"
drepos = GitHub.repos("JuliaDiffEq", auth = auth)[1]

@info("$(length(drepos)) repos acquired")

"The repositories that have been modified successfully."
mrepos = GitHub.Repo[]

original_file = nothing

for r in drepos

    #=
    if r.name == "PoissonRandom.jl"
        continue
    end
    =#

    printstyled("Checking ", color = 2, bold = true); println(r.name)

    global original_file # for debugging if needed - this is not meant for much reuse

    github_compat_c = Base64.base64encode(correct_c)

    try

        GitHub.create_file(r,
                        ".github/workflows/CompatHelper.yml",
                        params = Dict(
                                :message => "Add CompatHelper.jl to repo",
                                :content => github_compat_c,
                                :sha => original_file.sha),
                        auth = auth
        )


        original_file = GitHub.file(r, "CITATION.bib", auth = auth)

    catch e

        printstyled("No CompatHelper created\n", color = 1) # if no citation is found, don't do anything

        continue

    end

    push!(mrepos, r)

end

mrepos
```

what's the right way to get a sha?

**Comment by asinghvi17** [comment]
https://github.com/staticfloat/SHA.jl

`bytes2hex(sha256(::String))`

**Comment by ChrisRackauckas** [comment]
Thanks! This thread will be a useful future reference.

**Comment by asinghvi17** [comment]
You don't need the SHA when creating a file though

**Comment by ChrisRackauckas** [comment]
then that's a bug in Github.jl: it throws an error. It seems like the SHA is ignored though.

**Comment by asinghvi17** [comment]
Interesting.  Could you post the error?

**Comment by ChrisRackauckas** [comment]
It just throws an error saying that a SHA is required. It would take a bit to dig that back up.

**Pull request merged**
